### ISSUE TITLE
Chart version not updated to consume app release 3.2.0

### ISSUE THREAD

**Issue by arjungangisetty** [optimizely/optimizely-agent-helm#19]
Helm chart version needs a bump to consume traceId/spanId log updates released in 3.2.0 version. Any chance of quick revision to this file?
https://github.com/optimizely/optimizely-agent-helm/blob/main/Chart.yaml

```
appVersion: 3.2.0
version: 1.3.0
```
cc @pulak-opti

**Comment by pulak-opti** [comment]
Hi @arjungangisetty 
Helm chart is published with the latest Agent version.

**Comment by arjungangisetty** [comment]
Thanks for the swift update @pulak-opti
